name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Increase Swap (fix broken pipe)
        run: |
          sudo dd if=/dev/zero of=/swapfile bs=1M count=4096
          sudo chmod 600 /swapfile
